# TODO https://www.reddit.com/r/archlinux/comments/5r5ep8/make_your_arch_fonts_beautiful_easily/

- name: /etc/localtime
  file:
    src: /usr/share/zoneinfo/America/Chicago
    dest: /etc/localtime
    state: link

- name: systemd-networkd
  systemd:
    name: systemd-networkd
    enabled: yes
    state: started
  when: network

- name: mkdir
  command: "mkdir -p /etc/systemd/system/getty@tty1.service.d"

- name: "arch-common : config"
  include_role:
    name: common 
    tasks_from: file
  with_items:
    - { path: /etc/locale.gen, onchange: locale-gen }
    - { path: /etc/locale.conf }
    - { path: /etc/sysctl.d/99-sysctl.conf, onchange: sysctl --system }
    - { path: /etc/systemd/network/20-wired.network, onchange: systemctl restart systemd-networkd, when: network }
    - { path: /etc/systemd/system/getty@tty1.service.d/getty.conf }

- name: user shane
  become: yes
  user:
    name: shane
    append: yes
    groups:
      - users
      - audio
      - input
      - kvm
      - optical
      - storage
      - video
      - systemd-journal
    shell: /bin/bash
    expires: -1

- name: "arch-common : sudoers"
  become: yes
  copy:
    dest: /etc/sudoers.d/shane
    content: "shane ALL=(ALL) NOPASSWD:ALL\n"

- name: install core packages
  become: yes
  pacman:
    name:
      - grub
      - parted
      - sudo
      - hwinfo
      - time
      - htop
      - zsh
      - vim
      - tmux
      - openssh
      - git
      - the_silver_searcher
      - docker
    state: present

- name: install font packages
  pacman:
    name:
      - ttf-font-awesome
      - ttf-ubuntu-font-family
      - ttf-dejavu
      - ttf-liberation
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-extra
    state: present

- name: install vm guest packages
  pacman:
    name:
      - systemd-swap
      - open-vm-tools
      - xf86-input-vmmouse
      - xf86-video-vmware
    state: present
  when: virtualmachine

- name: vmtoolsd service
  systemd:
    name: vmtoolsd
    enabled: yes
    state: started
  when: virtualmachine

- name: install gui packages
  become: yes
  pacman:
    name:
      - xorg-xev
      - rxvt-unicode
      - termite
      - dmenu
      - i3status
      - code
      - qpdfview
    state: present

- name: "arch-common : yay"
  include_role:
    name: yay

- name: install aur packages
  become: yes
  become_user: shane
  yay:
    name:
      - yay
      - google-chrome
      - google-cloud-sdk
      - arch-silence-grub-theme
      - gotop-bin
      - i3-gaps
      - spotify

- name: "arch-common : grub"
  include_role:
    name: common 
    tasks_from: file
  with_items:
    - { path: /etc/default/grub, onchange: grub-mkconfig -o /boot/grub/grub.cfg }
  when: grub

- name: "arch-common : ssh"
  include_role:
    name: common
    tasks_from: file
  with_items:
    - { path: /etc/ssh/ssh_config }
  when: ssh
